### ISSUE TITLE
normalization of output

### ISSUE THREAD

**Issue by aemoor** [Kingsford-Group/ribomap#5]
I saw that the ribosome abundance (rabd) in the ribomap output stats file is not TPM normalized in contrast to the transcript abundance (tabd). For the subsequent TE caluclation these differently normalized values are utilized together. May I ask for the underlying reasons for this choice of procedure?

Thanks

**Comment by how-wonderful** [comment]
Hi Andreas,
Admittedly, the definition of TE can be improved. Currently there is no universal definition of translational efficiency. Broadly speaking, TE is defined as the ratio between ribosome abundance and transcript abundance. Our proposed calculation is only one way of doing it by using total ribosome loads as ribosome abundance. An alternative proposal is to use ribosome density as a ribosome abundance. That is the total ribosome footprint counts divided by the length of the coding region, and translational efficiency can thus be defined as the ratio between ribosome density and transcript abundance. Luckily Ribomap provides various intermediate statistics, so that the user can compute a desired measurement easily, like an alternative translational efficiency estimation.

**Comment by aemoor** [comment]
Thanks for your reply. I would like to compute differential TE across conditions and therefore need the (raw) read counts of the ribosomal reads. Can you guide me in retrieving them in the ribomap intermediate statistics or do I have to compute them based on the stat output file. Thanks again for your efforts.

**Comment by how-wonderful** [comment]
Hi Andreas,
You can find that in XXX.stats under rabd.
Thanks again for using Ribomap!

**Comment by aemoor** [comment]
Ok thanks. The general problem that I'm trying to solve is that I have RiboSeq data for multiple replicates of treatment and control and would like to use RiboMap and its output for identifying differential TE. Is there any sensible way of doing this with isoform-level data? All existing tools make use of gene-level raw counts and seem inappropriate for the ribomap output. Due to the lack of normalization of the ribosome abundance in ribomap it also does not make sense to compare the ribomap output directly across multiple replicates/conditions. What do you suggest for downstream analysis of multiple samples?

Thanks

**Comment by how-wonderful** [comment]
Hi Andreas,
Several tools exist for differential translation analysis. They usually take two matrices as input, one for Ribo-seq raw counts, and one for RNA-seq. Here, one dimension of the matrix is the list of transcript, and another dimension is the number of samples under different conditions. You can take Ribomap's output and Sailfish's output, extract the raw counts, and feed it into differential analysis tools.

Here's a list of existing tools:
- [**Babel**](https://cran.r-project.org/web/packages/babel/index.html)
- [**RiboDiff**](https://github.com/ratschlab/RiboDiff)
- [**Xtail**](https://github.com/xryanglab/xtail)
- [**Riborex**](https://github.com/smithlabcode/riborex)
