### ISSUE TITLE
Relative abundance of isoforms (cf the article about Ribomap)

### ISSUE THREAD

**Issue by AlexandraBomane** [Kingsford-Group/ribomap#6]
Hello !

I want to know how I can get the percentages of relative abundances of isoforms as in the Supplementary Figure 3 of "Isoform-level Ribosome Occupancy Estimation Guided by Transcript Abundance with Ribomap".

Because I don't understand how to interpret the relative abundance from Sailfish's result.

Another question : can I visualize triplet periodicity with the outputs ?

Thanks,
Alexandra

**Comment by how-wonderful** [comment]
Hi Alexandra,
I'm confused about your first question. Supplementary Figure 3 is "An illustration of when estimating ribosome profile on a gene level will fail", it is not a percentage of relative abundance. 

Ribomap provides one measurement of ribosome abundance, which is ribosome loads --- the total ribosome counts on a transcript. You can get it from XXX.stats (rabd). If you prefer to compute ribosome density, you can divide the ribosome loads with the CDS length of a transcript.

However, the definition of _relative_ abundance in ribo-seq is not clear. The relevant concept TPM is for transcript abundance, which stands for transcript per million, which you can find an explanation in here https://www.biostars.org/p/171766/#171792. Ribosome abundance is different because ribosome abundance depends on both transcript abundance and translation speed.

**Comment by AlexandraBomane** [comment]
Hi how-wonderful and thanks for your answer,

The supplementary figure 3 is at page 10 of the article and its legend are " An example of isoform level ribosome profiles for gene RPL37A (ENSG00000197756.5) produced by Ribomap and Star Prime on the Hela cell data (GSM546920) from [11]. The isoforms are listed in order of their relative abundance (value shown next to the transcript ID) estimated from Sailfish [27], and the isoform diagram is shown in between the Ribomap profile and Star prime profile. While Ribomap maps the footprints to the more abundant transcripts, Star prime as- signs footprint reads to a single candidate location at random, leaving two of the expressed transcripts almost ribosome-free (A, C), two of the unexpressed transcripts with the highest ribosome loads (E, F), and a surprisingly huge pile-up at the end of transcript ENST00000491306, inconsistent with its surrounding ribosome pile-ups (D). Profile plot is shown in UCSC Genome Browser [17]. "

And I want to understand the percentages next to transcript_id (how did you get them ?).

How can I visualize the translation speed with the outputs ?

Thanks,
Alexandra

**Comment by how-wonderful** [comment]
Hi Alexandra,
The percentages are computed from Sailfish's TPM value (normalized for this gene, such that the sum is 100 percent). 
You can visualize ribosome profiles with the `ribo profile` in _XXX.base_ or _XXX.codon_ for individual transcripts.
Thanks for your interests for using Ribomap!
